version: "3.8"

services:
  app:
    container_name: "${PROJECT_NAME}_react"
    networks:
      # Define the network on which traefik is going to operate.
      - web
    image: ${PROJECT_NAME}
    environment:
      REACT_APP_NAME: $REACT_APP_NAME
    build:
      context: .
      target: development
    volumes:
      - ./app:/app
    labels:
      # Enable handler entrypoint on http.
      - "traefik.http.routers.${REACT_NAME}_app-http.entrypoints=web"
      # Define handler http host.
      # Define http middleware and redirection to https.
      - "traefik.http.routers.${REACT_NAME}_app-http.rule=Host(`${REACT_BASE_URL}`)"
      - "traefik.http.routers.${REACT_NAME}_app-http.middlewares=${REACT_NAME}_app-https"
      - "traefik.http.middlewares.${REACT_NAME}_app-https.redirectscheme.scheme=https"
      # Enable handler entrypoint on https.
      - "traefik.http.routers.${REACT_NAME}_app.entrypoints=websecure"
      # Define handler host.
      - "traefik.http.routers.${REACT_NAME}_app.rule=Host(`${REACT_BASE_URL}`)"
      # Instructs Traefik that the current router is dedicated to HTTPS requests only.
      - "traefik.http.routers.${REACT_NAME}_app.tls=true"
      # Set service port for loadbalancer
      - "traefik.http.services.${PROJECT_NAME}_app.loadbalancer.server.port=3000"
      # Define on which network Traefik is operating.
      - "traefik.docker.network=web"

networks:
  web:
    external: true
  internal: