version: "3.8"

services:
  app:
    container_name: "${PROJECT_NAME}_react"
    image: app-dev
    environment:
        x: $REACT_APP_NAME
    build:
      context: .
      target: development
    volumes:
      - ./app:/app
    ports:
      - 3000:3000